# fly.toml app configuration file generated for devops-ca1 on 2023-12-03T16:16:14+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "devops-ca1"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048

[[services.http_checks]]
  interval = "120s"
  grace_period = "100s"
  method = "get"
  path = "/"
  protocol = "http"
  timeout = "50s"
  tls_skip_verify = false